version: '3'

services:
  mongodb:
    image: mongo:7.0.2-jammy
    volumes:
      - './data:/data/db'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password

  flask_app:
    build: .
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://admin:admin_password@mongodb:27017
    depends_on:
      - mongodb